name: bloc_weather
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  bloc: ^8.1.4
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  http: ^1.2.2
  hydrated_bloc: ^9.1.5
  json_annotation: ^4.9.0
  path_provider: ^2.1.5
  weather_repository:
    path: packages/weather_repository
  

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.13
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
